import { Inter } from "next/font/google";
import "../styles/globals.css";
import { DiscordProvider } from "../context/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Discord App blockchain",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DiscordProvider>{children}</DiscordProvider>
      </body>
    </html>
  );
}
